project_id = "tuascnmjgbarrtwlxzcx"

[functions.ai-coach]
verify_jwt = false

[functions.generate-questions]
verify_jwt = false

[functions.generate-lesson]
verify_jwt = false

[functions.create-paytr-token]
verify_jwt = false

[functions.paytr-callback]
verify_jwt = false
